### ISSUE TITLE
Several methods are broken.

### ISSUE THREAD

**Issue by dead-claudia** [vladocar/nanoJS#10]
Just a heads up, here's a list of methods that won't work:

- [`.getAttr()` doesn't actually return its result](https://github.com/vladocar/nanoJS/blob/master/src/nanoJS.js#L24).
- [`.offset()` has a similar problem](https://github.com/vladocar/nanoJS/blob/master/src/nanoJS.js#L99).
- Unlike [`.addClass()`](https://github.com/vladocar/nanoJS/blob/master/src/nanoJS.js#L44-L49), [`.toggleClass()`](https://github.com/vladocar/nanoJS/blob/master/src/nanoJS.js#L54) and [`.removeClass()`](https://github.com/vladocar/nanoJS/blob/master/src/nanoJS.js#L59) don't have full implementations.
- You have an extra unhelpful right parenthesis at the end of your style declaration for [`.animate()`](https://github.com/vladocar/nanoJS/blob/master/src/nanoJS.js#L34). Note that this is probably more efficient to just do `i.style.transition = ...`, etc. instead.

**Comment by isiahmeadows** [comment]
Oh, and similar is the case with `.offset()`.

**Comment by vladocar** [comment]
Thanks! Noted. I'm working on it.

I need to provide more documentation offset works like this:
$("#b").offset();
$("#c").css("width:" + offset.width + "px");

**Comment by vladocar** [comment]
.getAttr() fixed.

**Comment by crazy4groovy** [comment]
Ya, I just noticed .offset is pretty strange/ might not work? And no tests for it either.

**Comment by vladocar** [comment]
@crazy4groovy Yes, offset is little strange but it works.
