### ISSUE TITLE
Logo For nanoJS

### ISSUE THREAD

**Issue by iqbalhood** [vladocar/nanoJS#16]
Hi, I'm Interested your Minimal standalone JS library for DOM manipulation. Can I Contribute a Logo For This Project ?

**Comment by vladocar** [comment]
Yes, absolutely. Not really a logo but I made this: https://vladocar.github.io/nanoJS/nanoJS.png

**Comment by iqbalhood** [comment]
Okay I Will Try Do The Best For You :)

**Comment by vladocar** [comment]
Thanks 👍

**Comment by iqbalhood** [comment]
Hello Sir @vladocar ,
These are my logo proposal for your application. If there any revision, please just tell it.


![nano](https://user-images.githubusercontent.com/1563756/40760065-30b91fac-64bf-11e8-9b64-0202736bb6ae.gif)
![nanojs](https://user-images.githubusercontent.com/1563756/40760066-30ed00ce-64bf-11e8-97c1-4a401e257359.gif)
