### ISSUE TITLE
Logo Contribution For nanoJS

### ISSUE THREAD

**Issue by iqbalhood** [vladocar/nanoJS#20]
Hello Sir @vladocar ,
These are my logo proposal for your application. If there any revision, please just tell it.
![nano](https://user-images.githubusercontent.com/1563756/40770385-b4b98e66-64e4-11e8-8f50-7a1b40c50d67.gif)
![nanojs](https://user-images.githubusercontent.com/1563756/40770387-b4f0ec6c-64e4-11e8-87b1-a52a3524f090.gif)

**Comment by vladocar** [comment]
I absolutely love it :) Great job! 

Do you also have the vector files? You can send me everything via email so I can put them in the logo folder. This is my mail: vladocar@gmail.com 
Or you prefer you can do merge request with the logo folder.

**Comment by iqbalhood** [comment]
Hello sir, Thanks For Choosing My Logo. I Hope u can use my logo in this project. I Have Sent Email With Editable File To You :)

**Comment by seymourpoler** [comment]
niceee!!!!

**Comment by iqbalhood** [comment]
Hello sir, Thanks for your approval. If you need some help feel free to ask me :)

**Comment by vladocar** [comment]
Thank you for the logos :) 👍
