### ISSUE TITLE
When doing $(this) it throws an error. I think this is much needed.

### ISSUE THREAD

**Issue by munawar-js** [vladocar/nanoJS#21]
<img width="782" alt="screen shot 2018-06-01 at 12 32 36 am" src="https://user-images.githubusercontent.com/6573105/40802501-6464cb20-6533-11e8-94fa-70d85b9432e7.png">
<img width="534" alt="screen shot 2018-06-01 at 12 32 53 am" src="https://user-images.githubusercontent.com/6573105/40802502-64987b1e-6533-11e8-9526-73cf4bb65d6e.png">
<img width="253" alt="screen shot 2018-06-01 at 12 33 07 am" src="https://user-images.githubusercontent.com/6573105/40802503-64ce686e-6533-11e8-9688-be1e675edfc3.png">

Its a awesome lib, using in my new project

**Comment by vladocar** [comment]
Hi I made new update now $(this) will work.
