### ISSUE TITLE
typo on `att`, `getAtt` and `removeAtt`?

### ISSUE THREAD

**Issue by tunnckoCore** [vladocar/nanoJS#3]
First time seeing someone is using `att` instead of `attr` as in most places.

Probably a typo or it's intentional?

https://github.com/vladocar/nanoJS/blob/master/src/nanoJS.js#L17

**Comment by vladocar** [comment]
Not a typo. Originally when I made https://github.com/vladocar/picoCSS the idea was to make everything small, even the naming system. Yes "attr" will be the correct jQuery name. But the purpose of this project was not to copy jQuery rather to use jQuery logic and motivate developers to personalise this project to fit their needs. 

However I will consider your suggestion if most common occurrence is attr why confuse everyone.

**Comment by tunnckoCore** [comment]
Okwy. I'm getting the point, but still. I don't like when find such decisions by some authors.

"Just because of that" to be different. It's not matter of copying or not. It's a matter of "standards", or more called conventions. And yea, it may be just one character less, but such things are muscle memory anyway (not to mention it's not just muscle memory, [but eye/mind memory too](https://en.m.wikipedia.org/wiki/Typoglycemia)). :)

Don't get me hard. I just like to point that things.

**Comment by vladocar** [comment]
The truth of the matter is that I named all the methods based on some my logic, I didn't care to be diverse / different, just works or doesn't. 

However you point is valid. Naming conventions are important also "muscle memory". So building a usable product is more important than saving one character for performance. 

Result: I will change the name.
