### ISSUE TITLE
Repo needs some cleanup

### ISSUE THREAD

**Issue by chrisdothtml** [vladocar/nanoJS#32]
Some things I've noticed:

- ~[bower](https://bower.io) is deprecated, the configuration and install instructions should be removed (npm/yarn should be primary method of installation)~
- ~No module support. This is pretty standard for libraries these days, and makes it properly usable with bundlers like webpack. example:~

```javascript
if (typeof exports === 'object' && typeof module !== 'undefined')
  // CommonJS
else if (typeof define === 'function' && define.amd)
  // amd
```

- Lots of scattered html files throughout the repo, makes navigating it confusing
- `package.json` should contain `scripts` for running tests, building dist files, etc

Totally willing to open a PR for these things if you're open to it

**Comment by vladocar** [comment]
Yes sure, I'm always open for new suggestions and improvements. Thanks!

**Comment by chrisdothtml** [comment]
@vladocar What do you currently use to minify/process your source files (both for the nano source and the docs site)?

**Comment by vladocar** [comment]
Sites like https://jscompress.com that use UglifyJS3.
