### ISSUE TITLE
parent() and siblings()

### ISSUE THREAD

**Issue by bw1984** [vladocar/nanoJS#33]
any chance we could get these added? I personally use this quite a lot since the vanilla JS version adds a lot of repetition but this often comes in handy. or are these outside of scope for this lib?

**Comment by vladocar** [comment]
Hi, I just added parent() to the library. About the siblings() can be useful but I'm not sure if is often used.

**Comment by bw1984** [comment]
cool. im just basically after a way to target all parallel elements, excluding the original element. parent() gets me halfway there i just need to figure out an efficient way to traverse back down and somehow include some sort of (':not(this)') modifier.

just to give you a use-case, we use siblings a lot when building things like accordions, tabs, general navigation etc... so that we can add an 'active' class to the clicked element, whilst simultaneously removing it from any siblings (which may have previously been 'active')

i have small snippets to accomplish this, just thought it may be useful in the lib

**Comment by vladocar** [comment]
In the future that will possible with :has and :not CSS selectors. But today you need some JavaScript function to select  the previous and next siblings. If I find some clean solution/function for the siblings I will add it to the library.

**Comment by bw1984** [comment]
https://gist.github.com/cferdinandi/6203237

could be stripped down a bit further but thats basically the jist

**Comment by bw1984** [comment]
also;

```
Array.prototype.filter.call(el.parentNode.children, function(child){
  return child !== el;
});
```
(from http://youmightnotneedjquery.com/)

**Comment by vladocar** [comment]
siblings() added.
