### ISSUE TITLE
Some blank fields per NPM on amazon's C9 w/ace

### ISSUE THREAD

**Issue by Mirv** [vladocar/nanoJS#38]
Hi - would like to use your library for some dom traversal & eventhandling.

I not much of a NPM user myself but the cloud9 service I use has it already installed - so I ran your instructions per `README.md` & it appears there are some missing fields.

I checked your history on the `package.json` & the first & latest do in fact appear to be lacking at least the `README` field.

```
mirv:~/workspace (nanojs) $ npm i @vladocar/nanojs
/home/ubuntu/workspace
└── @vladocar/nanojs@1.0.4 

npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/workspace/package.json'
npm WARN workspace No description
npm WARN workspace No repository field.
npm WARN workspace No README data
npm WARN workspace No license field.
```

I'll see if I can PR this stuff later today.

**Comment by vladocar** [comment]
Ok, thanks!

**Comment by Mirv** [comment]
So I put down a new install just to be sure I'm ok in my env & then I noticed in your npm distribution your `package.json` is wildly different than your github.

My recommendation is to remove the npm distro or archive it till you get it caught up with the github repo - possibly from the `npm i @vladocar/nanojs` instruction from the github repo till you get it up to speed.

Contents I see ...
```

  "name": "@vladocar/nanojs",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/vladocar/nanoJS.git"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "version": "1.0.4"
}
```

Which might mean I still have something wrong with my env - but this definitely doesn't match your github file.

**Comment by vladocar** [comment]
It looks identical https://github.com/vladocar/nanoJS/blob/master/package.json just yours is ordered alphabetically: name, repository, scripts, version.

**Comment by Mirv** [comment]
Negative ... see line #4   "description": "Minimal standalone JS library for DOM manipulation" ...

You probably want to diff them?

**Comment by vladocar** [comment]
I lost track of what we want to achieve. I'm not familiar how cloud9 works but you can probably do "npm init" when you are inside the project folder and set all the parameters inside package.json. Alternatively you just need nanoJS.js file. It can also be accessed via cdn https://unpkg.com/@vladocar/nanojs@1.0.8/src/nanoJS.min.js

**Comment by Mirv** [comment]
Thanks for the options, probably won't stick with nano.
