### ISSUE TITLE
this.value and return this

### ISSUE THREAD

**Issue by cbkmutlu** [vladocar/nanoJS#39]
Firstly sorry for english. I'll try to my best.

For example in parent function is setting
this.value = [this.value[0].parentNode];
and
return this;
that's ok but,

When i try coding like that;

var temp = $('button.primary');
temp.on('click', function() {
or
$('button.primary').on('click', function() {
console.log( temp.parent() );
});

This code is working at the first time. But if you continue the click, the parent is climbing. But if var temp include the click event all okey.
What could i do about that?

**Comment by vladocar** [comment]
I'm sorry, I don't understand what you trying  to accomplish?

**Comment by cbkmutlu** [comment]
These are my javascript codes what i want to use
```
window.onload = function() {
  var button = $('button.primary');
  
  button.on('click', function() {
   console.log( button.parent() );
  });
}
```

That code is not working well. The parent is climbing when your every click. I am not trying to accomplish something. It was just debug for my main code. If i solve this my code will work fine.

**Comment by vladocar** [comment]
Ok, I understand now. It's true it's climbing to every parent element. I need to fix this..

Try this inside nanoJS:

parent: function () {
    return  $(this.value[0].parentNode);
  }

**Comment by cbkmutlu** [comment]
Oh finally. Its ok now. Let me some commits and it will be perfect. Thank you.
