### ISSUE TITLE
Where did the "1.2KB compressed" figure come from?

### ISSUE THREAD

**Issue by dead-claudia** [vladocar/nanoJS#9]
Here's the numbers I'm getting:

- 2601 bytes raw uncompressed
- 677 bytes raw + gzip
- 1781 bytes minified uncompressed
- 573 bytes minified + gzip

(1.2 KB seems absurd for a library that's this small.)

**Comment by vladocar** [comment]
Yes, you are right 1.2 Kb was minified before I added some methods. I made an error and used the word "compressed" but in reality was minified. Good thing it is twice less than I declared  :)

Did you use https://closure-compiler.appspot.com to measure gzip?

**Comment by dead-claudia** [comment]
> Yes, you are right 1.2 Kb was minified before I added some methods. I made an error and used the word "compressed" but in reality was minified. Good thing it is twice less than I declared :)

True.

Just for future reference, minifying is general obfuscation to reduce code size, and compression is in reference to general purpose data compression. It's considered best practice to serve your assets compressed, since it's a lot less data over the wire, and gzip is fast enough it's something you can do transparently in real time (compressing and decompressing faster than you can send/receive the data). It also helps that server-side compression has been supported in browsers even as far back as IE8.

> Did you use https://closure-compiler.appspot.com to measure gzip?

Nope, just the command line `gzip`.

My command lines looked like this, in case you're curious (should work on anything remotely Unix-like, including macOS, Linux, and Cygwin):

```sh
# Raw, uncompressed
curl -sS https://raw.githubusercontent.com/vladocar/nanoJS/master/src/nanoJS.js | wc -c
# Raw, compressed
curl -sS https://raw.githubusercontent.com/vladocar/nanoJS/master/src/nanoJS.js | gzip | wc -c
# Minified, uncompressed
curl -sS https://raw.githubusercontent.com/vladocar/nanoJS/master/src/nanoJS.min.js | wc -c
# Minified, compressed
curl -sS https://raw.githubusercontent.com/vladocar/nanoJS/master/src/nanoJS.min.js | gzip | wc -c
```

**Comment by vladocar** [comment]
Thanks for the command line tips. I didn't know that. 

Yes, I do know the difference between gzip and minifying. Ha,ha I've minifying by hand even before were tools for minifying :) 

> Just for future reference, minifying is general obfuscation to reduce code size, and compression is in reference to general purpose data compression. It's considered best practice to serve your assets compressed, since it's a lot less data over the wire, and gzip is fast enough it's something you can do transparently in real time (compressing and decompressing faster than you can send/receive the data). It also helps that server-side compression has been supported in browsers even as far back as IE8.

I love your explanation! Did you actually write this text about minifying & gzip?  If yes, you have some serious text documentation writing skills :)

**Comment by dead-claudia** [comment]
> I love your explanation! Did you actually write this text about minifying & gzip? If yes, you have some serious text documentation writing skills :)

Um...kinda...thanks, I guess...? 😄 (I kind of wrote that on the spot...)

**Comment by vladocar** [comment]
I was not joking.. that was really good end clear explanation. Maybe you have experience with Wikipedia editing or similar?

**Comment by dead-claudia** [comment]
I know you were serious. I was the one who wasn't. I *do* have a little bit of Wikipedia editing experience, but I've never been even remotely active as one. I do have [this massive bunch of docs](https://github.com/isiahmeadows/thallium/tree/master/docs) for a WIP framework I'm working on by myself, and I'm one of the maintainers of [Mithril](https://mithril.js.org/), a front-end framework.

In case you're curious, it just happens to be that I know how to write cohesively, and I have an experienced educator as a parent. Having decent writing and teaching ability helps a lot - the whole point of documentation is teaching the user how to use something and how it works.

**Comment by vladocar** [comment]
Yes, family influence is a key.  That explains it all.

Thallium has massive docs also I was not aware of Mithril. I will take a look.

Keep up the good work!
